kind: pipeline
type: docker
name: atlas

steps:
  - name: build_docker
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/heetch/atlas
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event: tag